/**
 * LOS ALAMITOS SCENARIO — GENERATED FROM THE SHARED RULES ENGINE.
 *
 * This module contains NO rule prose and NO status logic of its own. The
 * result label, explanation and sources are produced by calling the same
 * `evaluateRideDecision()` used by the Ride Check page at /rules, over the
 * same typed city-rule data in `src/data/cityRules.ts` and
 * `src/data/rideLocations.ts`.
 */

import { evaluateRideDecision } from "@/lib/evaluateRideDecision";
import type { RideDecisionInput } from "@/types/rideDecision";
import type { Scenario, ScenarioOutcomeLabel } from "@/types/scenarios";

/** The exact inputs the scenario asks about. */
export const LOS_ALAMITOS_SCENARIO_INPUT: RideDecisionInput = {
  ageYears: 17,
  classSelection: "class-3",
  cityId: "los-alamitos",
  location: "sidewalk",
  helmet: "yes",
};

/** Unobtrusive helper text shown with the generated scenario. */
export const SHARED_ENGINE_NOTE =
  "Result generated by the same Ride Check rules engine used on the Ride Check page.";

/**
 * Builds the scenario by evaluating the shared engine. Throws if the engine
 * cannot decide, so a data regression can never silently ship a hand-written
 * answer here.
 */
export function buildLosAlamitosScenario(): Scenario {
  const decision = evaluateRideDecision(LOS_ALAMITOS_SCENARIO_INPUT);
  if (!decision) {
    throw new Error("The shared ride-decision engine returned no decision for Los Alamitos.");
  }

  return {
    id: "los-alamitos-sidewalk",
    topic: "Los Alamitos sidewalk",
    question:
      "A 17-year-old wearing a helmet plans to ride a Class 3 e-bike on a Los Alamitos sidewalk. What does the Ride Check engine decide?",
    choices: [
      { id: "a", text: "Likely permitted, because the rider is wearing a helmet" },
      { id: "b", text: "Do not ride this setup on the sidewalk" },
      { id: "c", text: "Permitted below 5 mph" },
    ],
    correctChoiceId: "b",
    resultLabel: decision.overallLabel as ScenarioOutcomeLabel,
    explanation: decision.reasons.join(" "),
    sources: decision.sources,
    link: { label: "Check personalized rider rules", to: "/rules", search: { class: "3" } },
    derivedFrom: LOS_ALAMITOS_SCENARIO_INPUT,
    generatedNote: SHARED_ENGINE_NOTE,
  };
}
