/**
 * SHARED SOURCE REGISTRY FOR THE "SOURCES & METHODOLOGY" PAGE.
 *
 * This file adds no new legal rules and claims no new coverage. It reuses the
 * citations already stored in `californiaRules.ts` and the city records in
 * `cityRules.ts`, and attaches only a short "what the app uses this for" note
 * for display.
 */

import { CA_SOURCES, HELMET_UNDER_18_SOURCE, LEGAL_REVIEW_DATE } from "@/data/californiaRules";
import { CITY_RULES, CITY_RULES_VERIFIED_DATE } from "@/data/cityRules";
import type { CitySourceEntry, StatewideSourceEntry } from "@/types/sources";
import type { CityId } from "@/types/cityRules";

export { LEGAL_REVIEW_DATE, CITY_RULES_VERIFIED_DATE };

/** Plain-language usage notes, keyed by the citation string already in use. */
const STATEWIDE_USAGE: Record<string, string> = {
  "California Vehicle Code § 312.5":
    "Sets the pedal, motor-power, throttle and assisted-speed thresholds the Class Checker applies, including the Class 3 speedometer requirement.",
  "California Vehicle Code § 21213":
    "Supports the Ride Check age and operation rules, including the Class 3 minimum riding age and Class 3 helmet requirement.",
  "California Vehicle Code § 21212":
    "Supports the Ride Check helmet requirement for riders under 18, and the helmet note shown on classifier results.",
  "California Vehicle Code § 406":
    "Used only to explain that a vehicle failing the e-bike definition needs its category verified; the app never asserts a specific category.",
  "California Highway Patrol":
    "Background bulletin used to keep the classifier and Ride Check wording aligned with current statewide guidance.",
  "California DMV Driver's Handbook":
    "General rider-facing guidance referenced when the app tells a user to verify an unclassified vehicle with the DMV or CHP.",
};

/** Every statewide citation the classifier and Ride Check already cite. */
export const STATEWIDE_SOURCES: StatewideSourceEntry[] = [
  ...CA_SOURCES,
  HELMET_UNDER_18_SOURCE,
]
  // Avoid duplicate records if a citation appears in more than one list.
  .filter(
    (source, index, all) => all.findIndex((other) => other.url === source.url) === index,
  )
  .map((source) => ({
    citation: source.citation,
    label: source.label,
    url: source.url,
    usedFor: STATEWIDE_USAGE[source.citation] ?? source.label,
  }));

/** What each verified city's data supports inside Ride Check. */
const CITY_SUPPORT: Record<Exclude<CityId, "statewide-only">, string> = {
  anaheim:
    "Ride Check sidewalk, park, trail and local speed results for Anaheim, plus the Anaheim sidewalk scenario.",
  cypress: "Ride Check park and recreation-facility results for Cypress, plus the Cypress park scenario.",
  "garden-grove": "Ride Check park-property results for Garden Grove.",
  "los-alamitos":
    "Ride Check sidewalk, park and school results for Los Alamitos, including the Class 3 sidewalk prohibition, and the Los Alamitos scenario generated by the same decision engine.",
  stanton: "Ride Check sidewalk, park, trail and local speed results for Stanton.",
};

/** Verified Orange County coverage, derived from the shared city-rules records. */
export const CITY_SOURCES: CitySourceEntry[] = Object.values(CITY_RULES).map((city) => ({
  cityId: city.id,
  cityName: city.name,
  sources: [...city.sources],
  supports: CITY_SUPPORT[city.id],
}));

/** Page copy. Educational information only. */
export const SOURCES_PAGE = {
  heading: "Sources & methodology",
  intro:
    "E-Bike Ready OC is built from official California Vehicle Code sections and official Orange County city and ordinance sources. It is educational information, not legal advice. Laws, local codes and posted signs can change, so check the current official source before you ride.",
  methodology: [
    "The Class Checker applies the vehicle specifications you enter — operable pedals, motor watts, throttle behavior, assisted speeds, speedometer and advertised modifications — against the statewide e-bike definition.",
    "Ride Check combines rider age, vehicle class, helmet status, city and planned riding location into a single result.",
    "Any combination that is not covered by verified data, or that depends on on-site context such as a business district or a posted sign, returns \u201cVerify before riding.\u201d",
    "Decision Scenarios reuse the same Ride Check decision engine, so a scenario result cannot drift from the app's rules.",
    "The stopping-distance simulator is an educational physics model using reaction distance plus braking distance. It is not a legal rule and does not change any result.",
  ],
  coverageLimits: [
    "Only coverage that has been reviewed against an official source is shown. No other city is claimed as covered.",
    "An amber \u201cVerify before riding\u201d result is intentionally conservative: it means this app does not have enough verified information, not that riding is allowed.",
    "Always check current official sources and posted signs at the location where you plan to ride.",
    "If the wording here differs from the official source, the official source controls.",
  ],
} as const;
